### ISSUE TITLE
Using socket ABCI with v0.34 fails

### ISSUE THREAD

**Issue by conorsch** [informalsystems/CometMock#15]
I'm trying to use CometMock with [penumbra](https://github.com/penumbra-zone/penumbra), as a stand-in replacement for the `tendermint` binary in our integration test suite. Currently, our ABCI service only supports socket communication (although we're investigating adding gRPC support), but I haven't been able to get it working yet. I'm encountering an `invalid varint` error, which is coming from one of our dependencies relating to protobuf definitions (common when crossing the rust/go boundary over abci). 

Here's a branch where I've pushed the current state of play, so it's reproducible by others: https://github.com/penumbra-zone/penumbra/pull/2845 If you're willing to give the Penumbra build a shot, @p-offtermatt, see the steps at https://guide.penumbra.zone/main/pcli/install.html documenting dependencies.

**Comment by p-offtermatt** [comment]
This seems to have been an error with the timeout set by CometMock for InitChain. This was set to 500ms, which was too short, since the penumbra app needs roughly a single digit amount of seconds.

Solved in #19 

Feel free to reopen this if it turns out it doesn't solve your issue!
