### ISSUE TITLE
bug: Too many docker images with tags

### ISSUE THREAD

**Issue by Anmol1696** [informalsystems/CometMock#81]
## Overview
Currently if you see the docker images being released
<img width="1088" alt="Screenshot 2023-10-17 at 3 04 07 PM" src="https://github.com/informalsystems/CometMock/assets/10805402/f63b3034-b736-47ca-ab75-3b1ab5a3ee23">

Release page here: https://github.com/informalsystems/CometMock/pkgs/container/cometmock/versions?filters%5Bversion_type%5D=tagged

## Proposal
Ideally taged releases should be limited to:
* `0.x.x` versions
* `main`, `nightly`

**Comment by p-offtermatt** [comment]
Thanks for pointing this out! I agree with the Proposal, will change it like that.
